# Louis BAYLE, 2023-10-22
# ====================================================
# Run with docker-compose:
#
#   mkdir -p /data/docker
#   cd /data/docker
#   wget https://raw.githubusercontent.com/lbayle/codev/master/doc/docker/docker-compose.yml
#   wget https://raw.githubusercontent.com/lbayle/codev/master/doc/docker/mantis_codevtt_freshInstall.sql
#   docker-compose up -d
#   docker exec -i docker-mariadb-1 mysql -uroot -pmy_password --force bugtracker < mantis_codevtt_freshInstall.sql

version: '3.8'

services:
  # ---------------------------------------------------------
  # docker exec -i mariadb-codevtt mariadb -uroot -pmy_password --force bugtracker < mantis_codevtt_freshInstall.sql
  mariadb:
    image: mariadb:latest
    hostname: 'mariadb'
    container_name: mariadb-codevtt
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - codevtt_net
    volumes:
      - /data/docker/mariadb/mysql:/var/lib/mysql
      - /data/docker/mariadb/logs:/var/log/mariadb
      - /data/docker/mariadb/conf.d:/etc/mysql/conf.d

  # ---------------------------------------------------------
  mantis-codevtt:
    image: lbayle/codevtt:1.8.0
    hostname: 'mantis-codevtt'
    container_name: mantis-codevtt
    restart: unless-stopped
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          memory: 1G
    links:
      - mariadb
    networks:
      - codevtt_net
    volumes:
      - /data/docker/mantis-codevtt/logs-httpd:/var/log/httpd/
      - /data/docker/mantis-codevtt/logs:/tmp/codevtt/logs
      - /data/docker/mantis-codevtt/mantis/uploaded_files:/var/www/html/mantis/uploaded_files
      - /data/docker/mantis-codevtt/mantis/config:/var/www/html/mantis/config
      - /data/docker/mantis-codevtt/mantis/plugins:/var/www/html/mantis/plugins
      - /data/docker/mantis-codevtt/codevtt/config:/var/www/html/codevtt/config

# Development: CodevTT & MantisBT src code are not in the container to be easily accessed by IDE & git
#      - /data/docker/mantis-codevtt/codevtt:/var/www/html/codevtt
#      - /data/docker/mantis-codevtt/mantis/var/www/html/mantis


  # ---------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: 'phpmyadmin'
    container_name: phpmyadmin-codevtt
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=mantisbt
      - PMA_PASSWORD=mantisbt
    networks:
      - codevtt_net
    links:
      - mariadb
    volumes:
      - /data/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

networks:
  codevtt_net:
    name: codevtt_net
    driver: bridge

# end.
